@echo off
echo Preparing building environment...
call "%VS100COMNTOOLS%\vsvars32.bat" > nul:

echo Building test application...
devenv "Lab Project.sln" /rebuild Debug > nul:

echo Running test application...
"Debug\Lab Project.exe" %1 > "Data.txt"

echo Validating data from test application...
type "Data.txt" | "Validate.exe" > "Results.txt"